/*
 * graphicSettings.h
 *
 * Stylesheet für die Graphische Oberfläche
 *
 *  Created on: 06.01.2010
 *      Author: root
 */

#ifndef GRAPHICSETTINGS_H_
#define GRAPHICSETTINGS_H_

#define GWC_ROWS_PER_VIEW				5

#define GWC_FIRST_ROW_TOP				35

#define GWC_ROW_HEIGHT					30
#define GWC_ROW_MARGIN_TOP				5

#define GWC_ROW_LABEL_LEFT				5
#define GWC_ROW_LABEL_WIDTH				155
#define GWC_ROW_LABEL_FONT				&g_sFontCm14b
#define GWC_ROW_LABEL_COLOR				ClrWhite
#define GWC_ROW_LABEL_BACKGROUNDCOLOR	ClrBlack
#define GWC_ROW_LABEL_OUTLINECOLOR		ClrGray

#define GWC_ROW_VALUE_LEFT				200
#define GWC_ROW_VALUE_WIDTH				80
#define GWC_ROW_VALUE_FONT				&g_sFontCm14b
#define GWC_ROW_VALUE_COLOR				ClrWhite
#define GWC_ROW_VALUE_BACKGROUNDCOLOR	ClrBlack
#define GWC_ROW_VALUE_OUTLINECOLOR		ClrGray
#define GWC_ROW_VALUE_MAX_LENGTH		6

#define GWC_ROW_DECREASE_BUTTON_LEFT				165
#define GWC_ROW_DECREASE_BUTTON_WIDTH				30
#define GWC_ROW_DECREASE_BUTTON_FONT				&g_sFontCm14b
#define GWC_ROW_DECREASE_BUTTON_COLOR				ClrWhite
#define GWC_ROW_DECREASE_BUTTON_BACKGROUNDCOLOR		ClrRed
#define GWC_ROW_DECREASE_BUTTON_PUSHCOLOR			ClrGray
#define GWC_ROW_DECREASE_BUTTON_OUTLINECOLOR		ClrGray
#define GWC_ROW_DECREASE_BUTTON_SYMBOL				"-"
#define GWC_ROW_DECREASE_AUTOREPEAT					1

#define GWC_ROW_INCREASE_BUTTON_LEFT				285
#define GWC_ROW_INCREASE_BUTTON_WIDTH				30
#define GWC_ROW_INCREASE_BUTTON_FONT				&g_sFontCm14b
#define GWC_ROW_INCREASE_BUTTON_COLOR				ClrWhite
#define GWC_ROW_INCREASE_BUTTON_BACKGROUNDCOLOR		ClrGreen
#define GWC_ROW_INCREASE_BUTTON_PUSHCOLOR			ClrGray
#define GWC_ROW_INCREASE_BUTTON_OUTLINECOLOR		ClrGray
#define GWC_ROW_INCREASE_BUTTON_SYMBOL				"+"
#define GWC_ROW_INCREASE_AUTOREPEAT					1

#endif /* GRAPHICSETTINGS_H_ */
