/*
 * displayStyle.h
 *
 *  Created on: 19.02.2010
 *      Author: root
 */

#ifndef DISPLAYSTYLE_H_
#define DISPLAYSTYLE_H_

#include "grlib/grlib.h"
#include "grlib/checkbox.h"

#define DISPLAY_LINES_PER_VIEW						5
#define DISPLAY_TOP_OFFSET							27
#define DISPLAY_LINE_HEIGHT							30
#define DISPLAY_LINE_MARGIN							5

#define DISPLAY_BOOT_SCREEN_BACKGROUND_COLOR		ClrBlack
#define DISPLAY_BOOT_SCREEN_COLOR					ClrYellow
#define DISPLAY_BOOT_SCREEN_FONT					&g_sFontCm16

// MenuButton
#define DISPLAY_MENU_BUTTON_TOP						208
#define DISPLAY_MENU_BUTTON_LEFT					161
#define DISPLAY_MENU_BUTTON_WIDTH					157
#define DISPLAY_MENU_BUTTON_HEIGHT					30
#define DISPLAY_MENU_BUTTON_COLOR 					ClrWhite
#define DISPLAY_MENU_BUTTON_OUTLINE_COLOR			ClrGreen
#define DISPLAY_MENU_BUTTON_BACKGROUND_COLOR		ClrDarkGreen
#define DISPLAY_MENU_BUTTON_PUSH_COLOR				ClrLightGreen
#define DISPLAY_MENU_BUTTON_FONT					&g_sFontCm20b
#define DISPLAY_MENU_BUTTON_STYLE					PB_STYLE_FILL | PB_STYLE_OUTLINE | PB_STYLE_TEXT
#define DISPLAY_MENU_BUTTON_TEXT					"Menue"
#define DISPLAY_MENU_BUTTON_ACTION					vTouchLoadMenu

// SaveButton
#define DISPLAY_SAVE_BUTTON_TOP						208
#define DISPLAY_SAVE_BUTTON_LEFT					2
#define DISPLAY_SAVE_BUTTON_WIDTH					157
#define DISPLAY_SAVE_BUTTON_HEIGHT					30
#define DISPLAY_SAVE_BUTTON_COLOR 					ClrWhite
#define DISPLAY_SAVE_BUTTON_OUTLINE_COLOR			ClrGreen
#define DISPLAY_SAVE_BUTTON_BACKGROUND_COLOR		ClrDarkGreen
#define DISPLAY_SAVE_BUTTON_PUSH_COLOR				ClrLightGreen
#define DISPLAY_SAVE_BUTTON_FONT					&g_sFontCm20b
#define DISPLAY_SAVE_BUTTON_STYLE					(PB_STYLE_FILL | PB_STYLE_OUTLINE | PB_STYLE_TEXT)
#define DISPLAY_SAVE_BUTTON_TEXT					"Speichern"
#define DISPLAY_SAVE_BUTTON_ACTION					vTouchStoreValues

// DownButton
#define DISPLAY_DOWN_BUTTON_TOP						176
#define DISPLAY_DOWN_BUTTON_LEFT					288
#define DISPLAY_DOWN_BUTTON_WIDTH					30
#define DISPLAY_DOWN_BUTTON_HEIGHT					30
#define DISPLAY_DOWN_BUTTON_COLOR 					ClrWhite
#define DISPLAY_DOWN_BUTTON_OUTLINE_COLOR			ClrBlue
#define DISPLAY_DOWN_BUTTON_BACKGROUND_COLOR		ClrDarkBlue
#define DISPLAY_DOWN_BUTTON_PUSH_COLOR				ClrLightBlue
#define DISPLAY_DOWN_BUTTON_FONT					&g_sFontCm12
#define DISPLAY_DOWN_BUTTON_STYLE					(PB_STYLE_FILL | PB_STYLE_OUTLINE | PB_STYLE_TEXT)
#define DISPLAY_DOWN_BUTTON_TEXT					"Down"
#define DISPLAY_DOWN_BUTTON_ACTION					vPageDown

// UpButton
#define DISPLAY_UP_BUTTON_TOP						26
#define DISPLAY_UP_BUTTON_LEFT						288
#define DISPLAY_UP_BUTTON_WIDTH						30
#define DISPLAY_UP_BUTTON_HEIGHT					30
#define DISPLAY_UP_BUTTON_COLOR 					ClrWhite
#define DISPLAY_UP_BUTTON_OUTLINE_COLOR				ClrBlue
#define DISPLAY_UP_BUTTON_BACKGROUND_COLOR			ClrDarkBlue
#define DISPLAY_UP_BUTTON_PUSH_COLOR				ClrLightBlue
#define DISPLAY_UP_BUTTON_FONT						&g_sFontCm14
#define DISPLAY_UP_BUTTON_STYLE						(PB_STYLE_FILL | PB_STYLE_OUTLINE | PB_STYLE_TEXT)
#define DISPLAY_UP_BUTTON_TEXT						"Up"
#define DISPLAY_UP_BUTTON_ACTION					vPageUp

// Title
#define DISPLAY_TITLE_TOP							0
#define DISPLAY_TITLE_LEFT							0
#define DISPLAY_TITLE_WIDTH							GrContextDpyWidthGet(&g_sContext)
#define DISPLAY_TITLE_HEIGHT						24
#define DISPLAY_TITLE_COLOR 						ClrRed
#define DISPLAY_TITLE_OUTLINE_COLOR					ClrOrange
#define DISPLAY_TITLE_BACKGROUND_COLOR				ClrYellow
#define DISPLAY_TITLE_FONT							&g_sFontCm16
#define DISPLAY_TITLE_STYLE							(CANVAS_STYLE_TEXT | CANVAS_STYLE_FILL | CANVAS_STYLE_OUTLINE)
#define DISPLAY_TITLE_TEXT							"Luminary Webinterface"

// Title
#define DISPLAY_STATUS_MESSAGE_TOP					108
#define DISPLAY_STATUS_MESSAGE_LEFT					0
#define DISPLAY_STATUS_MESSAGE_WIDTH				GrContextDpyWidthGet(&g_sContext)
#define DISPLAY_STATUS_MESSAGE_HEIGHT				24
#define DISPLAY_STATUS_MESSAGE_COLOR 				ClrWhite
#define DISPLAY_STATUS_MESSAGE_OUTLINE_COLOR		ClrYellow
#define DISPLAY_STATUS_MESSAGE_BACKGROUND_COLOR		ClrRed
#define DISPLAY_STATUS_MESSAGE_FONT					&g_sFontCm16
#define DISPLAY_STATUS_MESSAGE_STYLE				(CANVAS_STYLE_TEXT | CANVAS_STYLE_FILL | CANVAS_STYLE_OUTLINE)
#define DISPLAY_STATUS_MESSAGE_TEXT					"Status Message"


// Label
#define DISPLAY_LABEL_LEFT							5
#define DISPLAY_LABEL_WIDTH							130
#define DISPLAY_LABEL_BACKGROUND_COLOR				ClrBlack
#define DISPLAY_LABEL_COLOR							ClrWhite
#define DISPLAY_LABEL_STYLE							(CANVAS_STYLE_TEXT | CANVAS_STYLE_FILL)
#define DISPLAY_LABEL_FONT							&g_sFontCm16
#define DISPLAY_LABEL_GROUP_FONT					&g_sFontCm18b

// Value
#define DISPLAY_VALUE_LEFT							140
#define DISPLAY_VALUE_WIDTH							140
#define DISPLAY_VALUE_BACKGROUND_COLOR				ClrDarkOliveGreen
#define DISPLAY_VALUE_OUTLINE_COLOR					ClrGreen
#define DISPLAY_VALUE_CHECKBOX_BACKGROUND_COLOR		ClrBlack
#define DISPLAY_VALUE_CHECKBOX_OUTLINE_COLOR		ClrWhite
#define DISPLAY_VALUE_COLOR							ClrBlack
#define DISPLAY_VALUE_PUSH_COLOR					ClrLightGreen;
#define DISPLAY_VALUE_FONT							&g_sFontCm16b
#define DISPLAY_VALUE_STYLE_NUMERIC					(CANVAS_STYLE_FILL | CANVAS_STYLE_OUTLINE | CANVAS_STYLE_TEXT)
#define DISPLAY_VALUE_STYLE_BOOLEAN					(CB_STYLE_FILL)
#define DISPLAY_VALUE_STYLE_HYPERLINK				(PB_STYLE_FILL | PB_STYLE_OUTLINE | PB_STYLE_TEXT)
#define DISPLAY_VALUE_TEXT_HYPERLINK				"open"
#define DISPLAY_VALUE_TEXT_LEN						16
#endif /* DISPLAYSTYLE_H_ */
